# SPDX-FileCopyrightText: Copyright (c) 2025-2026 The ProtoMotions Developers
# SPDX-License-Identifier: Apache-2.0

"""fbx_anim_to_motion: same-skeleton FBX animations -> .motion clips.

For robots generated by fbx2robot.py the animation FBXs share the
robot's own skeleton, so no cross-skeleton IK (GMR) is needed:

  per frame, per kept joint:  R_local = R_world(parent_kept)^T @ R_world(joint)
  (world-rotation copy — skipped intermediate bones fold in for free)
  -> joint rot mats + root pos -> fk_from_transforms_with_velocities
  -> height fix -> contact labels -> .motion

Body frames in the generated MJCF are world-aligned at the BIND pose,
so the joint zero configuration is the bind pose: the local rotation
above (bind-relative world delta in the parent's frame) IS the joint
rotation the MJCF expects.

One FBX per ufbx process (see RAPTOR_TIGER_PLAN.md landmines); this
script forks a worker per file.

Usage:
    python data/scripts/fbx_anim_to_motion.py --robot raptor \
        --anim-dir ~/sparkpack/UnrealExportedAssets/Raptor/Game/RaptorDinosaur/Animations/RootMotion \
        --output-dir data/motions/raptor
"""
import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

from data.scripts.fbx2robot import ROBOTS, _q_to_mat  # noqa: E402

WORKER_FLAG = "--_worker"


# ----------------------------------------------------------------------
# Worker: ONE fbx -> frames npz (runs in its own process, ufbx rules)
# ----------------------------------------------------------------------
def worker(fbx_path: str, robot: str, out_npz: str, fps: float):
    import gc

    gc.disable()
    import ufbx

    spec = ROBOTS[robot]
    keep = spec["keep"]
    keep_set = set(keep)
    keep_alive = []
    scene = ufbx.load_file(fbx_path)
    keep_alive.append(scene)

    ordered, seen = [], set()

    def _add(n):
        if n is None or id(n) in seen:
            return
        _add(n.parent)
        seen.add(id(n))
        ordered.append(n)

    for n in scene.nodes:
        _add(n)
    idx = {id(n): i for i, n in enumerate(ordered)}
    names = [n.name for n in ordered]
    parent_idx = [idx[id(n.parent)] if n.parent else -1 for n in ordered]

    anim = scene.anim
    t0, t1 = float(anim.time_begin), float(anim.time_end)
    num_frames = max(2, int(round((t1 - t0) * fps)) + 1)

    kept_rows = [i for i, nm in enumerate(names) if nm in keep_set]
    root_row = names.index(spec["root"])

    Rw_frames = np.zeros((num_frames, len(kept_rows), 3, 3))
    root_pos = np.zeros((num_frames, 3))
    kept_index = {row: k for k, row in enumerate(kept_rows)}

    for f in range(num_frames):
        t = t0 + min(f / fps, t1 - t0)
        Rw = [None] * len(ordered)
        pw = [None] * len(ordered)
        for i, node in enumerate(ordered):
            tr = node.evaluate_transform(anim, t)
            Rl = _q_to_mat(tr.rotation)
            tl = np.array(
                [tr.translation.x, tr.translation.y, tr.translation.z]
            )
            p = parent_idx[i]
            if p < 0:
                Rw[i], pw[i] = Rl, tl
            else:
                Rw[i] = Rw[p] @ Rl
                pw[i] = pw[p] + Rw[p] @ tl
            if i in kept_index:
                Rw_frames[f, kept_index[i]] = Rw[i]
        root_pos[f] = pw[root_row]

    np.savez(
        out_npz,
        rw=Rw_frames,
        root_pos=root_pos,
        kept=[names[r] for r in kept_rows],
        fps=fps,
        duration=t1 - t0,
    )
    sys.stdout.flush()
    os._exit(0)


# ----------------------------------------------------------------------
# Main: npz frames -> .motion via the robot's kinematic info
# ----------------------------------------------------------------------
def frames_to_motion(npz_path: Path, robot: str, bind_rw: dict, out: Path,
                     min_height: float):
    import torch

    from protomotions.components.pose_lib import (
        extract_kinematic_info,
        extract_qpos_from_transforms,
        fk_from_transforms_with_velocities,
    )
    from data.scripts.contact_detection import (
        compute_contact_labels_from_pos_and_vel,
    )

    spec = ROBOTS[robot]
    d = np.load(npz_path, allow_pickle=True)
    kept = list(d["kept"])
    rw = d["rw"]  # [T, K, 3, 3] world rotations, source axes
    root_pos = d["root_pos"] * 0.01  # cm -> m
    fps = float(d["fps"])

    if spec["up_axis"] == "y":
        C = np.array([[1, 0, 0], [0, 0, -1], [0, 1, 0]], dtype=float)
        rw = C[None, None] @ rw @ C.T[None, None]
        root_pos = root_pos @ C.T

    ki = extract_kinematic_info(f"protomotions/data/assets/mjcf/{robot}.xml")
    body_names = list(ki.body_names)
    order = [kept.index(b) for b in body_names]
    kpar = {b: None for b in body_names}
    # parent lookup straight from the MJCF kinematic info
    parents = list(ki.parent_indices) if hasattr(
        ki, "parent_indices") else None

    T = rw.shape[0]
    R = rw[:, order]  # [T, B, 3, 3] world, robot body order
    Rb = np.stack([bind_rw[b] for b in body_names])  # [B, 3, 3] bind world

    # world-aligned bind frames: joint world rotation relative to bind is
    # Rrel = Rw @ Rb^T; the local (parent-relative) joint rotation is
    # Rl = Rrel(parent)^T @ Rrel(child).
    Rrel = R @ np.transpose(Rb, (0, 2, 1))[None]
    joint_mats = np.zeros_like(Rrel)
    for bi, b in enumerate(body_names):
        pi = parents[bi] if parents is not None else -1
        if pi < 0:
            joint_mats[:, bi] = Rrel[:, bi]
        else:
            joint_mats[:, bi] = (
                np.transpose(Rrel[:, pi], (0, 2, 1)) @ Rrel[:, bi]
            )

    root_t = torch.from_numpy(root_pos).float()
    mats = torch.from_numpy(joint_mats).float()
    motion = fk_from_transforms_with_velocities(
        kinematic_info=ki,
        root_pos=root_t,
        joint_rot_mats=mats,
        fps=int(round(fps)),
        compute_velocities=True,
        velocity_max_horizon=3,
    )
    q = extract_qpos_from_transforms(
        ki, root_t, mats, multi_dof_decomposition_method="euler_xyz"
    )
    motion.dof_pos = q[:, 7:]
    dv = torch.zeros_like(motion.dof_pos)
    dv[1:] = (motion.dof_pos[1:] - motion.dof_pos[:-1]) * float(round(fps))
    motion.dof_vel = dv
    md = motion.to_dict() if hasattr(motion, "to_dict") else motion
    # ground: lowest body slightly above 0
    zmin = md["rigid_body_pos"][..., 2].min()
    if abs(float(zmin) - min_height) > 0.005:
        motion.fix_height(height_offset=-float(zmin) + min_height)
        md = motion.to_dict() if hasattr(motion, "to_dict") else motion
    motion.rigid_body_contacts = compute_contact_labels_from_pos_and_vel(
        motion.rigid_body_pos, motion.rigid_body_vel
    )
    motion.local_rigid_body_rot = None
    torch.save(motion.to_dict() if hasattr(motion, "to_dict") else motion, out)


def main():
    if WORKER_FLAG in sys.argv:
        i = sys.argv.index(WORKER_FLAG)
        worker(sys.argv[i + 1], sys.argv[i + 2], sys.argv[i + 3],
               float(sys.argv[i + 4]))
        return

    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--robot", choices=sorted(ROBOTS), required=True)
    ap.add_argument("--anim-dir", type=Path, required=True)
    ap.add_argument("--output-dir", type=Path, required=True)
    ap.add_argument("--fps", type=float, default=30.0)
    ap.add_argument("--min-height", type=float, default=0.01)
    ap.add_argument("--force-remake", action="store_true")
    args = ap.parse_args()

    spec = ROBOTS[args.robot]
    args.output_dir.mkdir(parents=True, exist_ok=True)
    tmp = args.output_dir / "_frames"
    tmp.mkdir(exist_ok=True)

    # Bind world rotations: one worker on the mesh FBX at t0 gives R==bind.
    bind_npz = tmp / "_bind.npz"
    if not bind_npz.exists() or args.force_remake:
        subprocess.run(
            [sys.executable, __file__, WORKER_FLAG, spec["fbx"],
             args.robot, str(bind_npz), "1.0"],
            check=True,
        )
    bd = np.load(bind_npz, allow_pickle=True)
    bind_rw = {n: bd["rw"][0, i] for i, n in enumerate(list(bd["kept"]))}
    if spec["up_axis"] == "y":
        C = np.array([[1, 0, 0], [0, 0, -1], [0, 1, 0]], dtype=float)
        bind_rw = {n: C @ r @ C.T for n, r in bind_rw.items()}

    files = sorted(args.anim_dir.glob("*.FBX")) + sorted(
        args.anim_dir.glob("*.fbx")
    )
    ok, failed = 0, []
    for f in files:
        if f.name.lower() == "bindpose.fbx":
            continue
        dst = args.output_dir / f"{f.stem}.motion"
        if dst.exists() and not args.force_remake:
            continue
        npz = tmp / f"{f.stem}.npz"
        try:
            subprocess.run(
                [sys.executable, __file__, WORKER_FLAG, str(f),
                 args.robot, str(npz), str(args.fps)],
                check=True, capture_output=True,
            )
            frames_to_motion(npz, args.robot, bind_rw, dst, args.min_height)
            ok += 1
            print(f"  ok: {dst.name}", flush=True)
        except Exception as exc:  # noqa: BLE001
            failed.append((f.name, str(exc)[:90]))
    print(f"converted: {ok} | failed: {len(failed)}")
    for n, r in failed[:15]:
        print(f"  FAIL {n}: {r}")


if __name__ == "__main__":
    main()
